apiVersion: apps/v1
kind: Deployment
metadata:
  name: http10-client
spec:
  selector:
    matchLabels:
      app: http10-client
  template:
    metadata:
      annotations:
        HTTP10: "1"
      labels:
        app: http10-client
    spec:
      containers:
      - name: http10-client
        image: {{ .Values.fortioImage }}
        args:
        - load
        - -qps
        - "{{ .Values.qps }}"
        - -t
        - "0"
        - -http1.0
        - fortio-server:8080/echo