apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        SECRET_TTL: 10m
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 2000m

    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
          maxReplicas: 10
        resources:
          limits:
            cpu: 6000m
            memory: 512Mi
          requests:
            cpu: 2000m
            memory: 512Mi

  addonComponents:
    grafana:
      enabled: true
    prometheus:
      enabled: false

  values:
    global:
      mtls:
        enabled: true
    grafana:
      enabled: true
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            orgId: 1
            url: http://istio-prometheus.istio-prometheus:9090
            access: proxy
            jsonData:
              timeInterval: 5s
            editable: true
            isDefault: true
