apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
        - name: redis
          image: redis:latest
          args:
            - sh
            - -c
            - |-
              while true; do
                printf "Pinging master: "
                redis-cli -h redis-master -a istio --no-auth-warning ping
                printf "Pinging slave: "
                redis-cli -h redis-slave -a istio --no-auth-warning ping
                sleep .5
              done