#!/bin/bash

set -eu

cd `mktemp -d`

echo "running in $PWD"

go mod init temp

cat <<EOF > tools.go
//go:build tools

package tools

import (
"github.com/golangci/golangci-lint/cmd/golangci-lint"
"golang.org/x/tools/cmd/goimports"
)
EOF


for import in $@; do
  go get "github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2"
  go get "golang.org/x/tools/cmd/goimports@v0.1.0"
done
go mod tidy

makebb "github.com/golangci/golangci-lint/cmd/golangci-lint" "golang.org/x/tools/cmd/goimports"
