apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
    spec:
      containers:
        - name: kafka
          image: howardjohn/kafka-perf-client
          imagePullPolicy: Always