apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: {{.Release.Namespace}}-sidecar
spec:
  egress:
  - hosts:
    - istio-system/istio-telemetry.istio-system
    - istio-system/istio-mixer.istio-system
    port:
      number: 9091
      name: grpc-mixer
      protocol: GRPC
  - hosts:
    - istio-system/istio-telemetry.istio-system
    - istio-system/istio-mixer.istio-system
    port:
      number: 15004
      name: grpc-mixer-mtls
      protocol: GRPC
