apiVersion: v1
kind: Service
metadata:
  name: fortio-server
  namespace: allow-external-traffic-b
spec:
  selector:
    app: fortio-server
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-server
  namespace: allow-external-traffic-b
  labels:
    app: fortio-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio-server
  template:
    metadata:
      name: fortio-server
      labels:
        app: fortio-server
    spec:
      containers:
        - name: fortio-server
          image:  {{ .Values.fortioImage }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fortio-gateway
  namespace: allow-external-traffic-b
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fortio
  namespace: allow-external-traffic-b
spec:
  hosts:
    - "*"
  gateways:
    - fortio-gateway
  http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          port:
            number: 8080
          host: fortio-server
