apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-traffic
  labels:
    app: external-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-traffic
  template:
    metadata:
      name: external-traffic
      labels:
        app: external-traffic
    spec:
      containers:
        - name: external-traffic
          image: fortio/fortio:latest_release
          args:
           - load
           - -qps
           - "{{ .Values.qps }}"
           - -t
           - "0"
           - {{ .Values.externalDestination }}